image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Compiling the code..."
    - dotnet build
    - echo "Compile complete."

unit-test:
  stage: test
  script:
    - echo "Running unit tests... "
    - dotnet test 
      --collect:"XPlat Code Coverage"
      --test-adapter-path:. 
      --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - 'dotnet tool run reportgenerator -reports:"**/cobertura-coverage.xml" -targetdir:"./coverage" --reporttypes:"Cobertura;HtmlInline;TextSummary"' # Generate Code Coverage Reports
    - "sed -n '/Summary/,/^$/p' coverage/Summary.txt"
    - echo "Unit tests complete."
  artifacts:
    when: always
    reports:
      junit:
        - ./**/*test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml
    paths:
      - "./coverage/*.*" # collect coverage HTMls
  coverage: '/All files\s+\|\s+\d+\.\d+/'
