image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Compiling the code..."
    - dotnet build
    - echo "Compile complete."
  allow_failure: false

unit-test:
  stage: test
  script:
    - echo "Running unit tests... "
    - dotnet test 
      --test-adapter-path:. 
      --collect="XPlat Code Coverage" 
      --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - dotnet tool run reportgenerator 
      -reports:"**/coverage.cobertura.xml" -targetdir:"..\artifacts\{assembly}/coverage" 
        --reporttypes:Cobertura' # Generate Code Coverage Reports 
    - echo "Unit tests complete."
  artifacts:
    when: always
    # paths:
    #   - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: "./coverage/Cobertura.xml"
