image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - tests
  - api

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Compiling the code..."
    - dotnet build
    - echo "Compile complete."

unit-test:
  stage: tests
  variables:
    COVERAGE_FLAG: "XPlat Code Coverage"
    LOGGER_FLAG: "junit;LogFilePath=../artifacts/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" 
  script:
    - echo "Running unit tests... "
    - dotnet test 
      --test-adapter-path:. 
      --logger:"$LOGGER_FLAG"
    - echo "Unit tests complete."
  artifacts:
    when: always
    paths:
      - /**/*test-result.xml
    reports:
      junit:
        - /**/*test-result.xml


  #     --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" 
  #     --logger:"$LOGGER_FLAG"'
  #   - echo "Unit tests complete."
  # artifacts:
  #   when: always
  #   paths:
  #     - ./**/*test-result.xml
  #     - $CI_PROJECT_DIR/junit/junit-test-result.xml
  #   reports:
  #     junit:
  #       - ./**/*test-result.xml
  #       - $CI_PROJECT_DIR/junit/junit-test-result.xml




# codecov:
#   stage: api
#   script:
#     - echo "Generating code coverage report..."
#     - curl -Os https://uploader.codecov.io/latest/linux/codecov
#     - chmod +x codecov
#     - ./codecov -t ${CODECOV_TOKEN}
#     - echo "Code coverage report complete."
