image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - api

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Compiling the code..."
    - dotnet build
    - echo "Compile complete."

unit-test:
  stage: test
  script:
    - echo "Running unit tests... "
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - echo "Unit tests complete."
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
api:
  stage: api
  script:
    - echo "Generating code coverage report..."
    - $ProgressPreference = 'SilentlyContinue' Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe .\codecov.exe
    - echo "Code coverage report complete."
